/**
 * Application identity + standing notices.
 *
 * Operational data always reads the live Supabase database via the server-only
 * service layer; marketing copy lives in `src/content/*` pending final
 * client-supplied wording. There is no staged or simulated mode: what renders
 * is what the platform really does.
 */

export const APP_NAME = 'Ask Juice Doctor AI';

/**
 * Standing safety + status notices — the single source of truth consumed by the
 * /disclaimer page so the wording can never drift between surfaces. Every line
 * is a statement of current fact; remove a line only when it stops being true.
 */
export const STANDING_NOTICES: readonly string[] = [
  'Not for emergency use — if this is an emergency, contact your local emergency services.',
  'Not a replacement for a healthcare professional’s judgement.',
  'AI responses are generated by a language model grounded in an approved evidence base and are not reviewed by a healthcare professional.',
  'Responses in other languages are AI-generated and not clinically human-reviewed — English is the reference version.',
  'Wearable device connections are not yet available.',
  'Voice conversations are planned and not yet available.',
  'Payments are recorded manually — no online payment is taken through the platform.',
];
