import type { Metadata } from 'next';
import { createMetadata } from '@/config/metadata';
import { LegalPage } from '@/components/sections/legal-page';
import { PROTOTYPE_NOTICES } from '@/config/app';

export const metadata: Metadata = createMetadata({
  title: 'Disclaimer',
  description: 'Important notices about this demonstration prototype.',
  path: '/disclaimer',
});

export default function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      intro="This is a demonstration prototype of the Ask Juice Doctor AI wellbeing platform. Please read the notices below before using it."
      sections={[
        {
          heading: 'Prototype for demonstration only',
          body: 'This environment is for demonstration purposes only. It is not a live clinical service. Features may be incomplete, and behaviour may change.',
        },
        {
          heading: 'Not for emergencies',
          body: 'Do not use this prototype in an emergency. If you or someone else may be in danger or need urgent medical help, contact your local emergency services immediately (for example, call 999 in the UK or 112 in the EU).',
        },
        {
          heading: 'Not medical advice',
          body: 'The specialists provide general wellbeing support only. They do not diagnose, prescribe, or replace the judgement of a qualified healthcare professional. Always seek professional advice for medical concerns.',
        },
        {
          heading: 'AI-generated responses',
          body: 'Responses are generated by an AI language model grounded in an approved evidence base. They are not yet reviewed by a healthcare professional. Responses in other languages are AI-translated and not clinically verified — English is the reference version.',
        },
        {
          heading: 'No live patient data; simulated wearables',
          body: 'No real patient records are used — all data is fictional or anonymised for demonstration. Wearable insights are simulated; no live device or Thryve connection is active. Voice conversations are planned and not yet connected.',
        },
        {
          heading: 'Summary of standing notices',
          body: PROTOTYPE_NOTICES.map((n) => `• ${n}`).join('\n'),
        },
      ]}
    />
  );
}
