import type { Metadata } from 'next';
import { createMetadata } from '@/config/metadata';
import { LegalPage } from '@/components/sections/legal-page';
import { STANDING_NOTICES } from '@/config/app';

export const metadata: Metadata = createMetadata({
  title: 'Disclaimer',
  description: 'Important notices about the Ask Juice Doctor AI platform.',
  path: '/disclaimer',
});

export default function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      intro="Please read these notices before using the platform."
      sections={[
        {
          heading: 'Not for emergencies',
          body: 'Do not use this platform in an emergency. If you or someone else may be in danger or need urgent medical help, contact your local emergency services immediately (for example, call 999 in the UK or 112 in the EU).',
        },
        {
          heading: 'Not medical advice',
          body: 'The specialists provide general wellbeing support only. They do not diagnose, prescribe, or replace the judgement of a qualified healthcare professional. Always seek professional advice for medical concerns.',
        },
        {
          heading: 'AI-generated responses',
          body: 'Responses are generated by an AI language model grounded in an approved evidence base. They are not reviewed by a healthcare professional. Responses in other languages are AI-translated and not clinically verified — English is the reference version.',
        },
        {
          heading: 'Your data',
          body: 'Information you enter is stored securely so your conversations, goals and plans continue between visits. Wearable device connections and voice conversations are not yet available; payments are recorded manually — no online payment is taken through the platform.',
        },
        {
          heading: 'Summary of standing notices',
          body: STANDING_NOTICES.map((n) => `• ${n}`).join('\n'),
        },
      ]}
    />
  );
}
